### PR TITLE
Updates for ROS Indigo and Baxter RSDK 1.1

### PR DESCRIPTION
**Pull request by ghost**
- Added pygame run dependancy
- Added character sanitation for difficulty mode
- Converted most OpenCV functions to OpenCV2
- Preemptively attempts to close Baxter's head camera to prevent 3 cameras powered at once
- Added celebratory head pan on win condition

### CODE REVIEW

**Comment by rethink-imcmahon** [comment]
Special thanks to @kdoelling for testing these Indigo changes, and providing very helpful feedback!

**Comment by rethink-imcmahon** [comment]
@rethink-rlinsalata or @chris-smith, would you mind giving these changes a look through?

**Comment by chris-smith** [comment]
I'm not very familiar with ros or opencv python implementations but these generally look good... Any reason for choosing queue size 10 for xdisplay? It doesn't seem to be published at a high rate. Presumably it's inconsequential...
 http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers#Choosing_a_good_queue_size

**Comment by rethink-imcmahon** [comment]
Thanks @chris-smith! Yep, queue size of 10 has been default rospy pub queue size when it is more important to preserve all of the messages rather than always having the most recent message (queue_size would be 1 in that instance).

**Pull request merged**
